version: '3.8'
services:
  app:
    container_name: nest-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - PORT=${PORT}
    volumes:
      - ./:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - bridge
    command: npm run start:dev
  postgres:
    container_name: postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    networks:
      - bridge
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
networks:
  bridge:
volumes:
  pgdata:
